version: "3"

services:
  # BETY rails frontend to the database
  bety:
    # build: . # to build after updating Dockerfile
    # image: bety_local-bety_local:latest # or pecan/bety:latest to pull from dockerhub (?)
    image: pecan/bety:${BRANCH:-latest}
    networks:
      - bety
    ports:
      - 8000
    environment:
      - UNICORN_WORKER_PROCESSES=1
      - SECRET_KEY_BASE=thisisnotasecret
      - PGUSER=bety
      - PGOPTIONS=-c search_path=ecosystem_observation_app # This sets the schema to use for PostgreSQL queries
      - PGDATABASE=postgres
      - PGHOST=host.docker.internal
      - PGPORT=19840     # OneDB Ecosystem Observation App - Yggdrasil - Development
#     - PGHOST=5432                 # Docker
    restart: unless-stopped

networks:
  bety:
  